# CFX-17.1 build 2016.04.12-14.50-136032
ANIMATION:
  Animate Camera = On
  Animation Bit Rate = 5152000
  Animation Filename = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/StaticMixer_001.can
  Animation Frame Pattern = IBBPBB
  Animation Frame Rate = 24
  Animation Hardcopy Filename = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/StaticMixer_001.wmv
  Animation Name = 
  Animation Quality = Medium
  Animation Speed Factor = 2.0
  Antialiasing = On
  Drop Last MPEG Frame = false
  Frame Increment = 1
  Hardcopy Tolerance = 0.0001
  Intermediate File Format = jpg
  Keep Intermediate Files = Off
  Keyframe List = KeyframeNo1,KeyframeNo2
  Local Output Directory = 
  Looping = Loop
  Looping Cycles = 1
  MPEG Height = 480
  MPEG Scale = 100
  MPEG Size = 640 x 480
  MPEG Width = 640
  Output Directory = .
  Output to User Directory = Off
  QAnim Frames = 20
  QAnim Looping = Bounce
  QAnim Looping Cycles = -1
  QAnim MPEG Filename = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/StaticMixer_001.wmv
  QAnim Object List = 
  QAnim Override Symbol = On
  QAnim Save MPEG = Off
  QAnim Symbol Size = 1.0
  QAnim Symbol Spacing = 0.6
  QAnim Symbol Type = Ball
  Save Hardcopy = On
  Screen Capture = Off
  Speed Adjustment Selection = Normal
  Speed Scaling Method = Distribute Frames Smoothly
  TimeAnim Control Case = 
  TimeAnim Control Variable = 
  TimeAnim Crank Angle Interval = 
  TimeAnim End Crank Angle = 
  TimeAnim End Time = 
  TimeAnim End Timestep = -1
  TimeAnim Frame Interval = 
  TimeAnim Frame Spacing = 
  TimeAnim Looping Cycles = 1
  TimeAnim MPEG Filename = 
  TimeAnim Number Of Frames = 21
  TimeAnim Save MPEG = Off
  TimeAnim Specify Range = Off
  TimeAnim Start Crank Angle = 
  TimeAnim Start Time = 
  TimeAnim Start Timestep = 0
  TimeAnim Time Interval = 
  TimeAnim Timestep Interval = 1
  Timestep Interpolation Method = Timestep
  Use Screen MPEG Size = Off
  Variable Bit Rate = On
  Video Format = wmv
  White Background = Off
END

>>>>>>>>>>>>>>> KEYFRAME OBJECT: START >>>>>>>>>>>>>>>
KEYFRAME:KeyframeNo1
  Keyframe Filename = KeyframeNo1.cst
  Keyframe Name = KeyframeNo1
  Number Of Frames = 20
END


>>>>>>>>>>>>>>> KEYFRAME FILE:   START >>>>>>>>>>>>>>>
# State file created:  2016/10/06 14:34:07
# CFX-17.1 build 2016.04.12-14.50-136032

COMMENT:User Data
  Comment Exists = True
  Comment Heading = User Data
  Heading Level = 1
END
CONTOUR:Slice Contour
  Apply Instancing Transform = On
  Clip Contour = Off
  Colour Map = Default Colour Map
  Colour Scale = Linear
  Colour Variable = Temperature
  Colour Variable Boundary Values = Hybrid
  Constant Contour Colour = Off
  Contour Range = Global
  Culling Mode = No Culling
  Domain List = /DOMAIN GROUP:All Domains
  Draw Contours = On
  Font = Sans Serif
  Fringe Fill = On
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Lighting = On
  Line Colour = 0, 0, 0
  Line Colour Mode = Default
  Line Width = 1
  Location List = /PLANE:Slice
  Max = 0.0 [K]
  Min = 0.0 [K]
  Number of Contours = 11
  Show Numbers = Off
  Specular Lighting = On
  Surface Drawing = Smooth Shading
  Text Colour = 0, 0, 0
  Text Colour Mode = Default
  Text Height = 0.024
  Transparency = 0.0
  Use Face Values = Off
  Value List = 0 [K],1 [K]
  Visibility = Off
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
DATA READER:
  Active Case Name = Case StaticMixer_001
  Append Results = False
  Apply X Offset = false
  Apply Y Offset = false
  Apply Z Offset = false
  Clear All Objects = False
  Construct Variables From Fourier Coefficients = True
  Current Case List = Case StaticMixer_001
  Current Case Name = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
  Current Results File = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
  Current Timestep = -1
  Current Timevalue = 0
  Edit Case Names = false
  File Angle Units = rad
  File Chemical Amount Units = mol
  File Current Units = A
  File Length Units = m
  File Light Units = cd
  File Mass Units = kg
  File Money Units = GBP
  File Solid Angle Units = sr
  File Temperature Units = K
  File Time Units = s
  Force File Reload = False
  Keep Camera Position = True
  Load Particle Tracks = true
  Multi Configuration File Load Option = Last Case
  Open in New View = true
  Open to Compare = false
  Reference Acoustic Pressure = 2.0e-5 [Pa]
  Reference Length = 1.0 [m]
  Reference Velocity = 1.0 [m s^-1]
  Timestep Match Criterion = Same Step
  Timestep Sync Mode = By Time Value
  Timevalue Match Criterion = Same Value
  CASE:Case StaticMixer_001
    Construct Variables From Fourier Coefficients = True
    Current Case Name = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
    Current Results File = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
    Current Timestep = -1
    Current Timevalue = 0
    File Angle Units = rad
    File Chemical Amount Units = mol
    File Current Units = A
    File Length Units = m
    File Light Units = cd
    File Mass Units = kg
    File Money Units = GBP
    File Solid Angle Units = sr
    File Temperature Units = K
    File Time Units = s
    Multi Configuration File Load Option = Last Case
    BOUNDARY:Default Domain Default
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    BOUNDARY:in1
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    BOUNDARY:in2
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    BOUNDARY:out
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:Assembly
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:Default 2D Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:in1 Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:in2 Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:out Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    DOMAIN:Default Domain
      Angle Definition Method = Instances in 360
      Apply Reflection = false
      Apply Rotation = true
      Apply Translation = false
      Axis From File = Custom
      Background Mesh Density = 2000
      Background Mesh Generation Method = Quasi Orthogonal
      Blade Aligned Variable Available = false
      Create Additional Turbo Variables = false
      Do Cylindrical Initialization = False
      Domain Type = Normal
      Full Circle = Off
      Hub Curve Mode = From Turbo Region
      Inlet Curve Mode = From Turbo Region
      Inlet Region = /DATA READER/CASE:Case StaticMixer_001/BOUNDARY:in1,/DATA \
READER/CASE:Case StaticMixer_001/BOUNDARY:in2
      Instance Definition = From File
      Linear Blade Aligned Variable Available = false
      Number of Components in 360 = 1
      Number of Copies = 1
      Number of Data Instances = 1
      Number of Passages in 360 = 1
      Number of Passages in Component = 1
      Outlet Curve Mode = From Turbo Region
      Outlet Region = /DATA READER/CASE:Case StaticMixer_001/BOUNDARY:out
      Principal Axis = Z
      Reflection Plane Option = From Plane
      Rotation Angle = 0 [degree]
      Rotation Axis From = 0.0, 0.0, 0.0
      Rotation Axis To = 1.0, 0.0, 0.0
      Rotation Axis Type = Coordinate Frame
      Shroud Curve Mode = From Turbo Region
      TBR User Theta Correction = 0.0
      Translation Vector = 0.0, 0.0, 0.0
      Turbo 360 Case without Periodics = false
      X = 0.0
      Y = 0.0
      Z = 0.0
    END
    PRIMITIVE2D:F1.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 1
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F2.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 2
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F3.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 3
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F4.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 4
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F5.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 5
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F6.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 6
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F7.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 7
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F8.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 8
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F9.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 9
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE3D:B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 1
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
  END
END
DEFAULT INSTANCE TRANSFORM:Default Transform
  Angle Definition Method = Instances in 360
  Apply Reflection = false
  Apply Rotation = true
  Apply Translation = false
  Full Circle = Off
  Instancing Info From Domain = true
  Number of Components in 360 = 12
  Number of Copies = 1
  Number of Passages in 360 = 12
  Number of Passages in Component = 1
  Principal Axis = Z
  Reflection Plane Option = From Plane
  Rotation Angle = 0 [degree]
  Rotation Axis From = 0.0, 0.0, 0.0
  Rotation Axis To = 1.0, 0.0, 0.0
  Rotation Axis Type = Coordinate Frame
  Translation Vector = 0.0, 0.0, 0.0
  X = 0.0
  Y = 0.0
  Z = 0.0
END
DEFAULT LEGEND:Default Legend View 1
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02 , 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 1
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = On
END
DEFAULT LEGEND:Default Legend View 2
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02, 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 2
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = true
END
DEFAULT LEGEND:Default Legend View 3
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02, 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 3
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = true
END
DEFAULT LEGEND:Default Legend View 4
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02, 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 4
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = true
END
DEFORMATION INFO:
  Deformation Scale = 1
END
FILE PROCESSING:
  Path Stack = .
  Processing Mode = None
  Supress File Replacement Warnings = false
END
LIBRARY:
  CEL:
    EXPRESSIONS:
      Accumulated Time Step = 32
      Current Time Step = 32
      Reference Pressure = 1 [atm]
      Sequence Step = 32
      Time = 0 [s]
      atstep = Accumulated Time Step
      ctstep = Current Time Step
      sstep = Sequence Step
      t = Time
    END
  END
END
MASS FLOW CALC OPTION ON PHYSICAL SURFACES:
  Option = Interpolated
END
PLANE:Slice
  Apply Instancing Transform = On
  Apply Texture = Off
  Blend Texture = On
  Bound Radius = 0.5 [m]
  Colour = 0.75, 0.75, 0.75
  Colour Map = Default Colour Map
  Colour Mode = Variable
  Colour Scale = Linear
  Colour Variable = Temperature
  Colour Variable Boundary Values = Hybrid
  Culling Mode = No Culling
  Direction 1 Bound = 1.0 [m]
  Direction 1 Orientation = 0 [degree]
  Direction 1 Points = 10
  Direction 2 Bound = 1.0 [m]
  Direction 2 Points = 10
  Domain List = /DOMAIN GROUP:All Domains
  Draw Faces = On
  Draw Lines = Off
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Invert Plane Bound = Off
  Lighting = On
  Line Colour = 0.0, 0.0, 0.0
  Line Colour Mode = User Specified
  Line Width = 1
  Max = 305 [K]
  Min = 295 [K]
  Normal = 0 , 0 , 1
  Option = Point and Normal
  Plane Bound = None
  Plane Type = Slice
  Point = 0 [m], 0 [m], 1.99 [m]
  Point 1 = 0 [m], 0 [m], 0 [m]
  Point 2 = 1 [m], 0 [m], 0 [m]
  Point 3 = 0 [m], 1 [m], 0 [m]
  Range = User Specified
  Render Edge Angle = 0 [degree]
  Specular Lighting = On
  Surface Drawing = Smooth Shading
  Texture Angle = 0
  Texture Direction = 0 , 1 , 0
  Texture Material = Metal
  Texture Position = 0 , 0
  Texture Scale = 1
  Texture Type = Predefined
  Tile Texture = Off
  Transform Texture = Off
  Transparency = 0.0
  Visibility = On
  X = 0.0 [m]
  Y = 0.0 [m]
  Z = 0.0 [m]
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
POINT:Point 1
  Apply Instancing Transform = On
  Colour = 1, 1, 0
  Colour Map = Default Colour Map
  Colour Mode = Constant
  Colour Scale = Linear
  Colour Variable = Pressure
  Colour Variable Boundary Values = Hybrid
  Culling Mode = No Culling
  Domain List = /DOMAIN GROUP:All Domains
  Draw Faces = On
  Draw Lines = Off
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Lighting = On
  Line Colour = 0, 0, 0
  Line Width = 2
  Max = 0.0 [Pa]
  Min = 0.0 [Pa]
  Node Number = 1
  Normalized = Off
  Option = XYZ
  Point = -1 [m], -1 [m], 1 [m]
  Point Symbol = Crosshair
  Range = Global
  Specular Lighting = On
  Surface Drawing = Smooth Shading
  Symbol Size = 1.0
  Transparency = 0.0
  Variable = Pressure
  Variable Boundary Values = Hybrid
  Visibility = Off
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
REPORT:
  Report Items = /TITLE PAGE,/REPORT/FILE INFORMATION OPTIONS,/REPORT/MESH \
STATISTICS OPTIONS,/REPORT/PHYSICS SUMMARY OPTIONS,/REPORT/SOLUTION SUMMARY \
OPTIONS,/COMMENT:User Data
  FILE INFORMATION OPTIONS:
    Include In Report = true
    This Exists = true
  END
  MESH STATISTICS OPTIONS:
    Include In Report = true
    Show Connectivity Number = false
    Show Edge Length Ratio = false
    Show Element Volume Ratio = false
    Show Max Face Angle = false
    Show Min Face Angle = false
    Show Number of Elements = true
    Show Number of Hexahedra = false
    Show Number of Nodes = true
    Show Number of Polyhedra = false
    Show Number of Pyramids = false
    Show Number of Tetrahedra = false
    Show Number of Wedges = false
    This Exists = true
  END
  PHYSICS SUMMARY OPTIONS:
    Include In Report = true
    Show Boundary Physics = true
    Show Domain Physics = true
    This Exists = true
  END
  PREVIEW:
    This Exists = true
    OUTPUT SETTINGS:
      Chart Image Type = png
      Chart Size = Same As Figure
      Custom Chart Size Height = 384
      Custom Chart Size Width = 512
      Custom Figure Size Height = 384
      Custom Figure Size Width = 512
      Figure Image Type = png
      Figure Size = 512 x 384
      Fit Views = false
      This Exists = true
    END
  END
  PUBLISH:
    Default Report Name = Report
    Generate CVF = false
    Report Format = HTML
    Report Path = ./Report.htm
    Save Images In Separate Folder = true
    This Exists = true
    OUTPUT SETTINGS:
      Chart Image Type = png
      Chart Size = Same As Figure
      Custom Chart Size Height = 384
      Custom Chart Size Width = 512
      Custom Figure Size Height = 384
      Custom Figure Size Width = 512
      Figure Image Type = png
      Figure Size = 512 x 384
      Fit Views = false
      This Exists = true
    END
  END
  SOLUTION SUMMARY OPTIONS:
    Include In Report = false
    Show Boundary Flow Summary = true
    Show Force and Torque Summary = false
    Show Forces = true
    Show Torques = true
    This Exists = true
  END
END
SCALAR VARIABLE:Absolute Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Approximated Mass Flow
  Boundary Values = Conservative
END
SCALAR VARIABLE:Area
  Boundary Values = Conservative
END
SCALAR VARIABLE:Aspect Ratio
  Boundary Values = Conservative
END
SCALAR VARIABLE:Connectivity Number
  Boundary Values = Conservative
END
SCALAR VARIABLE:Courant Number
  Boundary Values = Conservative
END
SCALAR VARIABLE:Density
  Boundary Values = Conservative
END
SCALAR VARIABLE:Dynamic Viscosity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Eddy Viscosity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Edge Length Ratio
  Boundary Values = Conservative
END
SCALAR VARIABLE:Element Volume Inverse
  Boundary Values = Conservative
END
SCALAR VARIABLE:Element Volume Ratio
  Boundary Values = Conservative
END
SCALAR VARIABLE:Force X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Force Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Force Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Heat Flux
  Boundary Values = Conservative
END
SCALAR VARIABLE:Interpolated Mass Flow
  Boundary Values = Conservative
END
SCALAR VARIABLE:Length
  Boundary Values = Conservative
END
SCALAR VARIABLE:Mass Flow
  Boundary Values = Conservative
END
SCALAR VARIABLE:Maximum Face Angle
  Boundary Values = Conservative
END
SCALAR VARIABLE:Mesh Expansion Factor
  Boundary Values = Conservative
END
SCALAR VARIABLE:Minimum Face Angle
  Boundary Values = Conservative
END
SCALAR VARIABLE:Normal X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Normal Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Normal Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Orthogonality Angle
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Shear Strain Rate
  Boundary Values = Conservative
END
SCALAR VARIABLE:Solver Yplus
  Boundary Values = Conservative
END
SCALAR VARIABLE:Specific Heat Capacity at Constant Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Specific Heat Capacity at Constant Volume
  Boundary Values = Conservative
END
SCALAR VARIABLE:Specific Volume
  Boundary Values = Conservative
END
SCALAR VARIABLE:Static Enthalpy
  Boundary Values = Conservative
END
SCALAR VARIABLE:Static Entropy
  Boundary Values = Conservative
END
SCALAR VARIABLE:Streamline Number on Streamline 1
  Boundary Values = Conservative
END
SCALAR VARIABLE:Temperature
  Boundary Values = Conservative
END
SCALAR VARIABLE:Thermal Conductivity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Time on Streamline 1
  Boundary Values = Conservative
END
SCALAR VARIABLE:Total Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Total Temperature
  Boundary Values = Conservative
END
SCALAR VARIABLE:Turbulence Eddy Dissipation
  Boundary Values = Conservative
END
SCALAR VARIABLE:Turbulence Eddy Frequency
  Boundary Values = Conservative
END
SCALAR VARIABLE:Turbulence Kinetic Energy
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Absolute Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Curl X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Curl Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Curl Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Divergence
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Invariant Q
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Lambda 2
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Normal Eigen Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Real Eigen Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Real Eigenvalue
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Stretched Swirling Strength
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Discriminant
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Normal X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Normal Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Normal Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Strength
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Vector X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Vector Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Vector Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Volume
  Boundary Values = Conservative
END
SCALAR VARIABLE:Volume Porosity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Volume of Finite Volumes
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Adjacent Temperature
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Heat Flux
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Heat Transfer Coefficient
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Shear X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Shear Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Shear Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Yplus
  Boundary Values = Conservative
END
SCALAR VARIABLE:Z
  Boundary Values = Conservative
END
STREAMLINE:Streamline 1
  Absolute Tolerance = 0.0 [m]
  Add Sample Vertex Normals = Off
  Apply Instancing Transform = On
  Colour = 0.75, 0.75, 0.75
  Colour Map = Default Colour Map
  Colour Mode = Variable
  Colour Scale = Linear
  Colour Variable = Total Temperature
  Colour Variable Boundary Values = Conservative
  Cross Periodics = On
  Culling Mode = No Culling
  Domain List = /DOMAIN GROUP:All Domains
  Draw Faces = On
  Draw Lines = Off
  Draw Streams = On
  Draw Symbols = Off
  Grid Tolerance = 0.01
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Lighting = On
  Line Colour = 0, 0, 0
  Line Width = 1
  Location List = /POINT:Point 1
  Locator Sampling Method = Vertex
  Max = 0.0 [K]
  Maximum Number of Items = 25
  Min = 0.0 [K]
  Number of Samples = 25
  Number of Sides = 8
  Random Seed = 1
  Range = Local
  Reduction Factor = 1.0
  Reduction or Max Number = Max Number
  Sample Spacing = 0.1
  Sampling Accuracy = High
  Sampling Aspect Ratio = 1
  Sampling Grid Angle = 0 [degree]
  Seed Point Type = Equally Spaced Samples
  Simplify Geometry = Off
  Specular Lighting = On
  Stream Drawing Mode = Line
  Stream Initial Direction = 0 , 0 , 0
  Stream Size = 1.0
  Stream Symbol = Ball
  Streamline Direction = Forward
  Streamline Maximum Periods = 20
  Streamline Maximum Segments = 10000
  Streamline Maximum Time = 0.0 [s]
  Streamline Solver Type = RungeKutta2
  Streamline Type = 3D Streamline
  Streamline Width = 2
  Surface Drawing = Smooth Shading
  Surface Streamline Direction = Forward and Backward
  Symbol Size = 1.0
  Symbol Start Time = 10.0 [s]
  Symbol Stop Time = -10.0 [s]
  Symbol Time Interval = 1.0 [s]
  Tolerance Mode = Grid Relative
  Transparency = 0.0
  Variable = Velocity
  Variable Boundary Values = Conservative
  Visibility = Off
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
SYMBOL CONTROL:
  Symbol Size = 1
END
SYSTEM COLOUR MAP:Blue to White
  Colour Map Colours = 0, 0, 0, 1, 1, 1, 1, 1, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:FLUENT Rainbow
  Colour Map Colours = 0, 0, 0, 1, 1, 0.278, 0, 1, 1, 1, 0.389, 0, 1, 0.5, 1, \
0.444, 0, 1, 0, 1, 0.667, 1, 1, 0, 1, 1, 1, 0, 0, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Greyscale
  Colour Map Colours = 0, 0.01, 0.01, 0.01, 1, 1, 0.99, 0.99, 0.99, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Inverse Greyscale
  Colour Map Colours = 0, 0.99, 0.99, 0.99, 1, 1, 0.01, 0.01, 0.01, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Inverse Rainbow
  Colour Map Colours = 0, 1, 0, 0, 1, 0.10, 1, 0.5, 0, 1, 0.25, 1, 1, 0, 1, \
0.43, 0.5, 1, 0, 1, 0.50, 0, 1, 0, 1, 0.56, 0, 1, 0.5, 1, 0.75, 0, 1, 1, 1, 0.90,\
 0, 0.5, 1, 1, 1, 0, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Inverse Rainbow 6
  Colour Map Colours = 0, 1, 0, 1, 1, 0.1, 1, 0, 0.5, 1, 0.2, 1, 0, 0, 1, 0.28,\
 1, 0.5, 0, 1, 0.4, 1, 1, 0, 1, 0.55, 0.5, 1, 0, 1, 0.6, 0, 1, 0, 1, 0.65, 0, 1, \
0.5, 1, 0.8, 0, 1, 1, 1, 0.92, 0, 0.5, 1, 1, 1, 0, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Minimal Map
  Colour Map Colours = 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Rainbow
  Colour Map Colours = 0, 0, 0, 1, 1, 0.10, 0, 0.5, 1, 1, 0.25, 0, 1, 1, 1, \
0.44, 0, 1, 0.5, 1, 0.50, 0, 1, 0, 1, 0.57, 0.5, 1, 0, 1, 0.75, 1, 1, 0, 1, 0.90,\
 1, 0.5, 0, 1, 1, 1, 0, 0, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Rainbow 6
  Colour Map Colours = 0, 0, 0, 1, 1, 0.08, 0, 0.5, 1, 1, 0.2, 0, 1, 1, 1, \
0.35, 0, 1, 0.5, 1, 0.4, 0, 1, 0, 1, 0.45, 0.5, 1, 0, 1, 0.6, 1, 1, 0, 1, 0.72, \
1, 0.5, 0, 1, 0.8, 1, 0, 0, 1, 0.9, 1, 0, 0.5, 1, 1, 1, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Transparency
  Colour Map Colours = 0, 1, 1, 1, 0, 1, 1, 1, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:White to Blue
  Colour Map Colours = 0, 1, 1, 1, 1, 1, 0, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Zebra
  Colour Map Colours = 0, 1, 1, 1, 1, 1.0, 0, 0, 0, 1
  Colour Map Divisions = 5
  Colour Map Storage Type = System
  Colour Map Type = Zebra
END
TITLE PAGE:
  Include ANSYS Logo = true
  Include Custom Logo = false
  Include Date = true
  Include TOC = true
  Show Captions in TOC = true
  Title Page Exists = true
END
UNIT SYSTEM:
  Preferred Units System = SI
  Update Units to Preferred = Off
END
VECTOR VARIABLE:Force
  Boundary Values = Conservative
END
VECTOR VARIABLE:Normal
  Boundary Values = Conservative
END
VECTOR VARIABLE:Pressure.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity u.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity v.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity w.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity.Curl
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity.Swirling Normal
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity.Swirling Vector
  Boundary Values = Conservative
END
VECTOR VARIABLE:Wall Shear
  Boundary Values = Conservative
END
VIEW:View 1
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 1,/PLANE:Slice,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Z
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = -0.17592,-0.424708,-0.820473,0.339851
    Scale = 0.247423
    Send To Viewer = True
  END
END
VIEW:View 2
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 2,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Y
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = 0.279848,-0.364705,-0.115917,0.880476
    Scale = 1
    Send To Viewer = True
  END
END
VIEW:View 3
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 3,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Y
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = 0.279848,-0.364705,-0.115917,0.880476
    Scale = 1
    Send To Viewer = True
  END
END
VIEW:View 4
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 4,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Y
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = 0.279848,-0.364705,-0.115917,0.880476
    Scale = 1
    Send To Viewer = True
  END
END
VIEWPORT MANAGER:
  Background Colour = 0.42, 0.55, 0.871
  Background Colour 2 = 1,1,1
  Background Colour Type = Top-Bottom Gradient
  Background Image = Mountains
  Background Image Mapping = Flat
  Background Image Type = Predefined
  Background Type = Colour
  Global Edge Colour = 0,0,0
  Global Text Colour = 0,0,0
  Maximized Viewport = -1
  Synchronize Camera = false
  Synchronize Visibility = true
  View Length Units = m
  Viewport 1 View = View 1
  Viewport 2 View = View 2
  Viewport 3 View = View 3
  Viewport 4 View = View 4
  Viewport Layout = No Split
  X Split = 0.5
  Y Split = 0.5
END
WIREFRAME:Wireframe
  Apply Instancing Transform = On
  Colour = 0, 0, 0
  Domain List = /DOMAIN GROUP:All Domains
  Edge Angle = 15 [degree]
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Line Colour Mode = Default
  Line Width = 1
  Show Surface Mesh = Off
  Visibility = On
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
<<<<<<<<<<<<<<< KEYFRAME FILE:   END   <<<<<<<<<<<<<<<

KEYFRAME:KeyframeNo2
  Keyframe Filename = KeyframeNo2.cst
  Keyframe Name = KeyframeNo2
END


>>>>>>>>>>>>>>> KEYFRAME FILE:   START >>>>>>>>>>>>>>>
# State file created:  2016/10/06 14:35:05
# CFX-17.1 build 2016.04.12-14.50-136032

COMMENT:User Data
  Comment Exists = True
  Comment Heading = User Data
  Heading Level = 1
END
CONTOUR:Slice Contour
  Apply Instancing Transform = On
  Clip Contour = Off
  Colour Map = Default Colour Map
  Colour Scale = Linear
  Colour Variable = Temperature
  Colour Variable Boundary Values = Hybrid
  Constant Contour Colour = Off
  Contour Range = Global
  Culling Mode = No Culling
  Domain List = /DOMAIN GROUP:All Domains
  Draw Contours = On
  Font = Sans Serif
  Fringe Fill = On
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Lighting = On
  Line Colour = 0, 0, 0
  Line Colour Mode = Default
  Line Width = 1
  Location List = /PLANE:Slice
  Max = 0.0 [K]
  Min = 0.0 [K]
  Number of Contours = 11
  Show Numbers = Off
  Specular Lighting = On
  Surface Drawing = Smooth Shading
  Text Colour = 0, 0, 0
  Text Colour Mode = Default
  Text Height = 0.024
  Transparency = 0.0
  Use Face Values = Off
  Value List = 0 [K],1 [K]
  Visibility = Off
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
DATA READER:
  Active Case Name = Case StaticMixer_001
  Append Results = False
  Apply X Offset = false
  Apply Y Offset = false
  Apply Z Offset = false
  Clear All Objects = False
  Construct Variables From Fourier Coefficients = True
  Current Case List = Case StaticMixer_001
  Current Case Name = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
  Current Results File = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
  Current Timestep = -1
  Current Timevalue = 0
  Edit Case Names = false
  File Angle Units = rad
  File Chemical Amount Units = mol
  File Current Units = A
  File Length Units = m
  File Light Units = cd
  File Mass Units = kg
  File Money Units = GBP
  File Solid Angle Units = sr
  File Temperature Units = K
  File Time Units = s
  Force File Reload = False
  Keep Camera Position = True
  Load Particle Tracks = true
  Multi Configuration File Load Option = Last Case
  Open in New View = true
  Open to Compare = false
  Reference Acoustic Pressure = 2.0e-5 [Pa]
  Reference Length = 1.0 [m]
  Reference Velocity = 1.0 [m s^-1]
  Timestep Match Criterion = Same Step
  Timestep Sync Mode = By Time Value
  Timevalue Match Criterion = Same Value
  CASE:Case StaticMixer_001
    Construct Variables From Fourier Coefficients = True
    Current Case Name = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
    Current Results File = C:/Users/tapeltie/Documents/THFL_SIM/Tutorial 2/\
StaticMixer_001.res
    Current Timestep = -1
    Current Timevalue = 0
    File Angle Units = rad
    File Chemical Amount Units = mol
    File Current Units = A
    File Length Units = m
    File Light Units = cd
    File Mass Units = kg
    File Money Units = GBP
    File Solid Angle Units = sr
    File Temperature Units = K
    File Time Units = s
    Multi Configuration File Load Option = Last Case
    BOUNDARY:Default Domain Default
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    BOUNDARY:in1
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    BOUNDARY:in2
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    BOUNDARY:out
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 0.2, 0.5, 1
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:Assembly
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:Default 2D Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:in1 Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:in2 Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    COMPOSITE:out Region
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    DOMAIN:Default Domain
      Angle Definition Method = Instances in 360
      Apply Reflection = false
      Apply Rotation = true
      Apply Translation = false
      Axis From File = Custom
      Background Mesh Density = 2000
      Background Mesh Generation Method = Quasi Orthogonal
      Blade Aligned Variable Available = false
      Create Additional Turbo Variables = false
      Do Cylindrical Initialization = False
      Domain Type = Normal
      Full Circle = Off
      Hub Curve Mode = From Turbo Region
      Inlet Curve Mode = From Turbo Region
      Inlet Region = /DATA READER/CASE:Case StaticMixer_001/BOUNDARY:in1,/DATA \
READER/CASE:Case StaticMixer_001/BOUNDARY:in2
      Instance Definition = From File
      Linear Blade Aligned Variable Available = false
      Number of Components in 360 = 1
      Number of Copies = 1
      Number of Data Instances = 1
      Number of Passages in 360 = 1
      Number of Passages in Component = 1
      Outlet Curve Mode = From Turbo Region
      Outlet Region = /DATA READER/CASE:Case StaticMixer_001/BOUNDARY:out
      Principal Axis = Z
      Reflection Plane Option = From Plane
      Rotation Angle = 0 [degree]
      Rotation Axis From = 0.0, 0.0, 0.0
      Rotation Axis To = 1.0, 0.0, 0.0
      Rotation Axis Type = Coordinate Frame
      Shroud Curve Mode = From Turbo Region
      TBR User Theta Correction = 0.0
      Translation Vector = 0.0, 0.0, 0.0
      Turbo 360 Case without Periodics = false
      X = 0.0
      Y = 0.0
      Z = 0.0
    END
    PRIMITIVE2D:F1.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 1
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F2.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 2
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F3.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 3
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F4.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 4
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F5.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 5
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F6.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 6
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F7.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 7
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F8.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 8
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE2D:F9.B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 9
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
    PRIMITIVE3D:B1.P3
      Apply Instancing Transform = On
      Apply Texture = Off
      Blend Texture = On
      Colour = 1, 0.5, 0
      Colour Map = Default Colour Map
      Colour Mode = Constant
      Colour Scale = Linear
      Colour Variable Boundary Values = Hybrid
      Culling Mode = No Culling
      Draw Faces = On
      Draw Lines = Off
      Instancing Transform = Default Transform
      Lighting = true
      Line Colour = 0, 0, 0
      Line Colour Mode = Default
      Line Width = 1
      Range = Global
      Render Edge Angle = 0 [degree]
      Set Number = 1
      Specular Lighting = On
      Surface Drawing = Smooth Shading
      Texture Angle = 0
      Texture Direction = 0.0, 1.0, 0.0
      Texture Material = Metal
      Texture Position = 0.0, 0.0
      Texture Scale = 1.0
      Texture Type = Predefined
      Tile Texture = Off
      Transform Texture = Off
      Transparency = 0.0
      Visibility = false
    END
  END
END
DEFAULT INSTANCE TRANSFORM:Default Transform
  Angle Definition Method = Instances in 360
  Apply Reflection = false
  Apply Rotation = true
  Apply Translation = false
  Full Circle = Off
  Instancing Info From Domain = true
  Number of Components in 360 = 12
  Number of Copies = 1
  Number of Passages in 360 = 12
  Number of Passages in Component = 1
  Principal Axis = Z
  Reflection Plane Option = From Plane
  Rotation Angle = 0 [degree]
  Rotation Axis From = 0.0, 0.0, 0.0
  Rotation Axis To = 1.0, 0.0, 0.0
  Rotation Axis Type = Coordinate Frame
  Translation Vector = 0.0, 0.0, 0.0
  X = 0.0
  Y = 0.0
  Z = 0.0
END
DEFAULT LEGEND:Default Legend View 1
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02 , 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 1
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = On
END
DEFAULT LEGEND:Default Legend View 2
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02, 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 2
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = true
END
DEFAULT LEGEND:Default Legend View 3
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02, 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 3
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = true
END
DEFAULT LEGEND:Default Legend View 4
  Colour = 0, 0, 0
  Font = Sans Serif
  Legend Aspect = 0.07
  Legend Format = %10.3e
  Legend Orientation = Vertical
  Legend Plot = /PLANE:Slice
  Legend Position = 0.02, 0.15
  Legend Resolution = 256
  Legend Shading = Smooth
  Legend Size = 0.6
  Legend Ticks = 5
  Legend Title = Legend
  Legend Title Mode = Variable and Location
  Legend X Justification = Left
  Legend Y Justification = Top
  Related Object = View 4
  Show Legend Units = On
  Text Colour Mode = Default
  Text Height = 0.024
  Text Rotation = 0
  Visibility = true
END
DEFORMATION INFO:
  Deformation Scale = 1
END
FILE PROCESSING:
  Path Stack = .
  Processing Mode = None
  Supress File Replacement Warnings = false
END
LIBRARY:
  CEL:
    EXPRESSIONS:
      Accumulated Time Step = 32
      Current Time Step = 32
      Reference Pressure = 1 [atm]
      Sequence Step = 32
      Time = 0 [s]
      atstep = Accumulated Time Step
      ctstep = Current Time Step
      sstep = Sequence Step
      t = Time
    END
  END
END
MASS FLOW CALC OPTION ON PHYSICAL SURFACES:
  Option = Interpolated
END
PLANE:Slice
  Apply Instancing Transform = On
  Apply Texture = Off
  Blend Texture = On
  Bound Radius = 0.5 [m]
  Colour = 0.75, 0.75, 0.75
  Colour Map = Default Colour Map
  Colour Mode = Variable
  Colour Scale = Linear
  Colour Variable = Temperature
  Colour Variable Boundary Values = Hybrid
  Culling Mode = No Culling
  Direction 1 Bound = 1.0 [m]
  Direction 1 Orientation = 0 [degree]
  Direction 1 Points = 10
  Direction 2 Bound = 1.0 [m]
  Direction 2 Points = 10
  Domain List = /DOMAIN GROUP:All Domains
  Draw Faces = On
  Draw Lines = Off
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Invert Plane Bound = Off
  Lighting = On
  Line Colour = 0.0, 0.0, 0.0
  Line Colour Mode = User Specified
  Line Width = 1
  Max = 305 [K]
  Min = 295 [K]
  Normal = 0 , 0 , 1
  Option = Point and Normal
  Plane Bound = None
  Plane Type = Slice
  Point = 0 [m], 0 [m], -1.99 [m]
  Point 1 = 0 [m], 0 [m], 0 [m]
  Point 2 = 1 [m], 0 [m], 0 [m]
  Point 3 = 0 [m], 1 [m], 0 [m]
  Range = User Specified
  Render Edge Angle = 0 [degree]
  Specular Lighting = On
  Surface Drawing = Smooth Shading
  Texture Angle = 0
  Texture Direction = 0 , 1 , 0
  Texture Material = Metal
  Texture Position = 0 , 0
  Texture Scale = 1
  Texture Type = Predefined
  Tile Texture = Off
  Transform Texture = Off
  Transparency = 0.0
  Visibility = On
  X = 0.0 [m]
  Y = 0.0 [m]
  Z = 0.0 [m]
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
POINT:Point 1
  Apply Instancing Transform = On
  Colour = 1, 1, 0
  Colour Map = Default Colour Map
  Colour Mode = Constant
  Colour Scale = Linear
  Colour Variable = Pressure
  Colour Variable Boundary Values = Hybrid
  Culling Mode = No Culling
  Domain List = /DOMAIN GROUP:All Domains
  Draw Faces = On
  Draw Lines = Off
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Lighting = On
  Line Colour = 0, 0, 0
  Line Width = 2
  Max = 0.0 [Pa]
  Min = 0.0 [Pa]
  Node Number = 1
  Normalized = Off
  Option = XYZ
  Point = -1 [m], -1 [m], 1 [m]
  Point Symbol = Crosshair
  Range = Global
  Specular Lighting = On
  Surface Drawing = Smooth Shading
  Symbol Size = 1.0
  Transparency = 0.0
  Variable = Pressure
  Variable Boundary Values = Hybrid
  Visibility = Off
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
REPORT:
  Report Items = /TITLE PAGE,/REPORT/FILE INFORMATION OPTIONS,/REPORT/MESH \
STATISTICS OPTIONS,/REPORT/PHYSICS SUMMARY OPTIONS,/REPORT/SOLUTION SUMMARY \
OPTIONS,/COMMENT:User Data
  FILE INFORMATION OPTIONS:
    Include In Report = true
    This Exists = true
  END
  MESH STATISTICS OPTIONS:
    Include In Report = true
    Show Connectivity Number = false
    Show Edge Length Ratio = false
    Show Element Volume Ratio = false
    Show Max Face Angle = false
    Show Min Face Angle = false
    Show Number of Elements = true
    Show Number of Hexahedra = false
    Show Number of Nodes = true
    Show Number of Polyhedra = false
    Show Number of Pyramids = false
    Show Number of Tetrahedra = false
    Show Number of Wedges = false
    This Exists = true
  END
  PHYSICS SUMMARY OPTIONS:
    Include In Report = true
    Show Boundary Physics = true
    Show Domain Physics = true
    This Exists = true
  END
  PREVIEW:
    This Exists = true
    OUTPUT SETTINGS:
      Chart Image Type = png
      Chart Size = Same As Figure
      Custom Chart Size Height = 384
      Custom Chart Size Width = 512
      Custom Figure Size Height = 384
      Custom Figure Size Width = 512
      Figure Image Type = png
      Figure Size = 512 x 384
      Fit Views = false
      This Exists = true
    END
  END
  PUBLISH:
    Default Report Name = Report
    Generate CVF = false
    Report Format = HTML
    Report Path = ./Report.htm
    Save Images In Separate Folder = true
    This Exists = true
    OUTPUT SETTINGS:
      Chart Image Type = png
      Chart Size = Same As Figure
      Custom Chart Size Height = 384
      Custom Chart Size Width = 512
      Custom Figure Size Height = 384
      Custom Figure Size Width = 512
      Figure Image Type = png
      Figure Size = 512 x 384
      Fit Views = false
      This Exists = true
    END
  END
  SOLUTION SUMMARY OPTIONS:
    Include In Report = false
    Show Boundary Flow Summary = true
    Show Force and Torque Summary = false
    Show Forces = true
    Show Torques = true
    This Exists = true
  END
END
SCALAR VARIABLE:Absolute Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Approximated Mass Flow
  Boundary Values = Conservative
END
SCALAR VARIABLE:Area
  Boundary Values = Conservative
END
SCALAR VARIABLE:Aspect Ratio
  Boundary Values = Conservative
END
SCALAR VARIABLE:Connectivity Number
  Boundary Values = Conservative
END
SCALAR VARIABLE:Courant Number
  Boundary Values = Conservative
END
SCALAR VARIABLE:Density
  Boundary Values = Conservative
END
SCALAR VARIABLE:Dynamic Viscosity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Eddy Viscosity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Edge Length Ratio
  Boundary Values = Conservative
END
SCALAR VARIABLE:Element Volume Inverse
  Boundary Values = Conservative
END
SCALAR VARIABLE:Element Volume Ratio
  Boundary Values = Conservative
END
SCALAR VARIABLE:Force X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Force Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Force Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Heat Flux
  Boundary Values = Conservative
END
SCALAR VARIABLE:Interpolated Mass Flow
  Boundary Values = Conservative
END
SCALAR VARIABLE:Length
  Boundary Values = Conservative
END
SCALAR VARIABLE:Mass Flow
  Boundary Values = Conservative
END
SCALAR VARIABLE:Maximum Face Angle
  Boundary Values = Conservative
END
SCALAR VARIABLE:Mesh Expansion Factor
  Boundary Values = Conservative
END
SCALAR VARIABLE:Minimum Face Angle
  Boundary Values = Conservative
END
SCALAR VARIABLE:Normal X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Normal Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Normal Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Orthogonality Angle
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Pressure.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Shear Strain Rate
  Boundary Values = Conservative
END
SCALAR VARIABLE:Solver Yplus
  Boundary Values = Conservative
END
SCALAR VARIABLE:Specific Heat Capacity at Constant Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Specific Heat Capacity at Constant Volume
  Boundary Values = Conservative
END
SCALAR VARIABLE:Specific Volume
  Boundary Values = Conservative
END
SCALAR VARIABLE:Static Enthalpy
  Boundary Values = Conservative
END
SCALAR VARIABLE:Static Entropy
  Boundary Values = Conservative
END
SCALAR VARIABLE:Streamline Number on Streamline 1
  Boundary Values = Conservative
END
SCALAR VARIABLE:Temperature
  Boundary Values = Conservative
END
SCALAR VARIABLE:Thermal Conductivity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Time on Streamline 1
  Boundary Values = Conservative
END
SCALAR VARIABLE:Total Pressure
  Boundary Values = Conservative
END
SCALAR VARIABLE:Total Temperature
  Boundary Values = Conservative
END
SCALAR VARIABLE:Turbulence Eddy Dissipation
  Boundary Values = Conservative
END
SCALAR VARIABLE:Turbulence Eddy Frequency
  Boundary Values = Conservative
END
SCALAR VARIABLE:Turbulence Kinetic Energy
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity u.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity v.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w.Gradient X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w.Gradient Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity w.Gradient Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Absolute Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Curl X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Curl Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Curl Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Divergence
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Invariant Q
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Lambda 2
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Normal Eigen Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Real Eigen Helicity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Real Eigenvalue
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Stretched Swirling Strength
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Discriminant
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Normal X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Normal Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Normal Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Strength
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Vector X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Vector Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Velocity.Swirling Vector Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:Volume
  Boundary Values = Conservative
END
SCALAR VARIABLE:Volume Porosity
  Boundary Values = Conservative
END
SCALAR VARIABLE:Volume of Finite Volumes
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Adjacent Temperature
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Heat Flux
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Heat Transfer Coefficient
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Shear X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Shear Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Wall Shear Z
  Boundary Values = Conservative
END
SCALAR VARIABLE:X
  Boundary Values = Conservative
END
SCALAR VARIABLE:Y
  Boundary Values = Conservative
END
SCALAR VARIABLE:Yplus
  Boundary Values = Conservative
END
SCALAR VARIABLE:Z
  Boundary Values = Conservative
END
STREAMLINE:Streamline 1
  Absolute Tolerance = 0.0 [m]
  Add Sample Vertex Normals = Off
  Apply Instancing Transform = On
  Colour = 0.75, 0.75, 0.75
  Colour Map = Default Colour Map
  Colour Mode = Variable
  Colour Scale = Linear
  Colour Variable = Total Temperature
  Colour Variable Boundary Values = Conservative
  Cross Periodics = On
  Culling Mode = No Culling
  Domain List = /DOMAIN GROUP:All Domains
  Draw Faces = On
  Draw Lines = Off
  Draw Streams = On
  Draw Symbols = Off
  Grid Tolerance = 0.01
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Lighting = On
  Line Colour = 0, 0, 0
  Line Width = 1
  Location List = /POINT:Point 1
  Locator Sampling Method = Vertex
  Max = 0.0 [K]
  Maximum Number of Items = 25
  Min = 0.0 [K]
  Number of Samples = 25
  Number of Sides = 8
  Random Seed = 1
  Range = Local
  Reduction Factor = 1.0
  Reduction or Max Number = Max Number
  Sample Spacing = 0.1
  Sampling Accuracy = High
  Sampling Aspect Ratio = 1
  Sampling Grid Angle = 0 [degree]
  Seed Point Type = Equally Spaced Samples
  Simplify Geometry = Off
  Specular Lighting = On
  Stream Drawing Mode = Line
  Stream Initial Direction = 0 , 0 , 0
  Stream Size = 1.0
  Stream Symbol = Ball
  Streamline Direction = Forward
  Streamline Maximum Periods = 20
  Streamline Maximum Segments = 10000
  Streamline Maximum Time = 0.0 [s]
  Streamline Solver Type = RungeKutta2
  Streamline Type = 3D Streamline
  Streamline Width = 2
  Surface Drawing = Smooth Shading
  Surface Streamline Direction = Forward and Backward
  Symbol Size = 1.0
  Symbol Start Time = 10.0 [s]
  Symbol Stop Time = -10.0 [s]
  Symbol Time Interval = 1.0 [s]
  Tolerance Mode = Grid Relative
  Transparency = 0.0
  Variable = Velocity
  Variable Boundary Values = Conservative
  Visibility = Off
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
SYMBOL CONTROL:
  Symbol Size = 1
END
SYSTEM COLOUR MAP:Blue to White
  Colour Map Colours = 0, 0, 0, 1, 1, 1, 1, 1, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:FLUENT Rainbow
  Colour Map Colours = 0, 0, 0, 1, 1, 0.278, 0, 1, 1, 1, 0.389, 0, 1, 0.5, 1, \
0.444, 0, 1, 0, 1, 0.667, 1, 1, 0, 1, 1, 1, 0, 0, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Greyscale
  Colour Map Colours = 0, 0.01, 0.01, 0.01, 1, 1, 0.99, 0.99, 0.99, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Inverse Greyscale
  Colour Map Colours = 0, 0.99, 0.99, 0.99, 1, 1, 0.01, 0.01, 0.01, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Inverse Rainbow
  Colour Map Colours = 0, 1, 0, 0, 1, 0.10, 1, 0.5, 0, 1, 0.25, 1, 1, 0, 1, \
0.43, 0.5, 1, 0, 1, 0.50, 0, 1, 0, 1, 0.56, 0, 1, 0.5, 1, 0.75, 0, 1, 1, 1, 0.90,\
 0, 0.5, 1, 1, 1, 0, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Inverse Rainbow 6
  Colour Map Colours = 0, 1, 0, 1, 1, 0.1, 1, 0, 0.5, 1, 0.2, 1, 0, 0, 1, 0.28,\
 1, 0.5, 0, 1, 0.4, 1, 1, 0, 1, 0.55, 0.5, 1, 0, 1, 0.6, 0, 1, 0, 1, 0.65, 0, 1, \
0.5, 1, 0.8, 0, 1, 1, 1, 0.92, 0, 0.5, 1, 1, 1, 0, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Minimal Map
  Colour Map Colours = 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Rainbow
  Colour Map Colours = 0, 0, 0, 1, 1, 0.10, 0, 0.5, 1, 1, 0.25, 0, 1, 1, 1, \
0.44, 0, 1, 0.5, 1, 0.50, 0, 1, 0, 1, 0.57, 0.5, 1, 0, 1, 0.75, 1, 1, 0, 1, 0.90,\
 1, 0.5, 0, 1, 1, 1, 0, 0, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Rainbow 6
  Colour Map Colours = 0, 0, 0, 1, 1, 0.08, 0, 0.5, 1, 1, 0.2, 0, 1, 1, 1, \
0.35, 0, 1, 0.5, 1, 0.4, 0, 1, 0, 1, 0.45, 0.5, 1, 0, 1, 0.6, 1, 1, 0, 1, 0.72, \
1, 0.5, 0, 1, 0.8, 1, 0, 0, 1, 0.9, 1, 0, 0.5, 1, 1, 1, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Transparency
  Colour Map Colours = 0, 1, 1, 1, 0, 1, 1, 1, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:White to Blue
  Colour Map Colours = 0, 1, 1, 1, 1, 1, 0, 0, 1, 1
  Colour Map Divisions = 2
  Colour Map Storage Type = System
  Colour Map Type = Gradient
END
SYSTEM COLOUR MAP:Zebra
  Colour Map Colours = 0, 1, 1, 1, 1, 1.0, 0, 0, 0, 1
  Colour Map Divisions = 5
  Colour Map Storage Type = System
  Colour Map Type = Zebra
END
TITLE PAGE:
  Include ANSYS Logo = true
  Include Custom Logo = false
  Include Date = true
  Include TOC = true
  Show Captions in TOC = true
  Title Page Exists = true
END
UNIT SYSTEM:
  Preferred Units System = SI
  Update Units to Preferred = Off
END
VECTOR VARIABLE:Force
  Boundary Values = Conservative
END
VECTOR VARIABLE:Normal
  Boundary Values = Conservative
END
VECTOR VARIABLE:Pressure.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity u.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity v.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity w.Gradient
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity.Curl
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity.Swirling Normal
  Boundary Values = Conservative
END
VECTOR VARIABLE:Velocity.Swirling Vector
  Boundary Values = Conservative
END
VECTOR VARIABLE:Wall Shear
  Boundary Values = Conservative
END
VIEW:View 1
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 1,/PLANE:Slice,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Z
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = -0.17592,-0.424708,-0.820473,0.339851
    Scale = 0.247423
    Send To Viewer = True
  END
END
VIEW:View 2
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 2,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Y
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = 0.279848,-0.364705,-0.115917,0.880476
    Scale = 1
    Send To Viewer = True
  END
END
VIEW:View 3
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 3,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Y
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = 0.279848,-0.364705,-0.115917,0.880476
    Scale = 1
    Send To Viewer = True
  END
END
VIEW:View 4
  Angular Coord Shift = 0.0
  Auto Center = false
  Axis Visibility = On
  Border Visibility = false
  Camera Mode = User Specified
  Clip Scene = false
  Coord Transform = Cartesian
  Hide Difference Case = false
  Highlight Type = Surface Mesh
  Is A Figure = false
  Light Angle = 50, 110
  Object Visibility List = /DEFAULT LEGEND:Default Legend View 4,/\
WIREFRAME:Wireframe
  Projection = Orthographic
  Ruler Visibility = On
  Standard View = Isometric Y
  CAMERA:
    Option = Pivot Point and Quaternion
    Pan = 0,0
    Pivot Point = 0,0,0
    Rotation = -90, 0, 0
    Rotation Quaternion = 0.279848,-0.364705,-0.115917,0.880476
    Scale = 1
    Send To Viewer = True
  END
END
VIEWPORT MANAGER:
  Background Colour = 0.42, 0.55, 0.871
  Background Colour 2 = 1,1,1
  Background Colour Type = Top-Bottom Gradient
  Background Image = Mountains
  Background Image Mapping = Flat
  Background Image Type = Predefined
  Background Type = Colour
  Global Edge Colour = 0,0,0
  Global Text Colour = 0,0,0
  Maximized Viewport = -1
  Synchronize Camera = false
  Synchronize Visibility = true
  View Length Units = m
  Viewport 1 View = View 1
  Viewport 2 View = View 2
  Viewport 3 View = View 3
  Viewport 4 View = View 4
  Viewport Layout = No Split
  X Split = 0.5
  Y Split = 0.5
END
WIREFRAME:Wireframe
  Apply Instancing Transform = On
  Colour = 0, 0, 0
  Domain List = /DOMAIN GROUP:All Domains
  Edge Angle = 15 [degree]
  Instancing Transform = /DEFAULT INSTANCE TRANSFORM:Default Transform
  Line Colour Mode = Default
  Line Width = 1
  Show Surface Mesh = Off
  Visibility = On
  OBJECT VIEW TRANSFORM:
    Apply Reflection = Off
    Apply Rotation = Off
    Apply Scale = Off
    Apply Translation = Off
    Principal Axis = Z
    Reflection Plane Option = XY Plane
    Rotation Angle = 0.0 [degree]
    Rotation Axis From = 0 [m], 0 [m], 0 [m]
    Rotation Axis To = 0 [m], 0 [m], 0 [m]
    Rotation Axis Type = Principal Axis
    Scale Vector = 1 , 1 , 1
    Translation Vector = 0 [m], 0 [m], 0 [m]
    X = 0.0 [m]
    Y = 0.0 [m]
    Z = 0.0 [m]
  END
END
<<<<<<<<<<<<<<< KEYFRAME FILE:   END   <<<<<<<<<<<<<<<

